branch-defaults:
  default:
    environment: fake-news-detection
    group_suffix: null
environment-defaults:
  fake-news-detection-dev:
    branch: null
    repository: null
  fake-news-detection-development:
    branch: null
    repository: null
global:
  application_name: fake-news-detection
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.9
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
