# Generated by Django 5.1.7 on 2025-03-15 00:35

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('prediction', models.CharField(max_length=10)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
